# version: '3'

services:
  api:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    environment:
      - POSTGRES_SERVER=db
      - REDIS_HOST=redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - mcpnetwork

  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mcp_db
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "mcp_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - mcpnetwork

  redis:
    image: redis:7.2
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - mcpnetwork

volumes:
  postgres_data:
  redis_data:

networks:
  mcpnetwork:
    driver: bridge  